# Generated by Django 4.2.14 on 2026-05-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_album_cover_photo_alter_photo_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
    ]
